config/routes.rb
Blog::Application.routes.draw do
  get 'sign-in' => 'sessions#new', as: 'sign_in'
  get 'sign-out' => 'sessions#destroy', as: 'sign_out'

  resources :articles
  resources :authors
  resources :sessions
  resources :categories
    
  root :to => 'Articles#index'
end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title,     presence: true,
                          length: { maximum: 140 }
  validates :author_id, presence: true
  validates :body,      presence: true
  
  belongs_to :author
  has_many   :categorizations, dependent: :destroy
  has_many   :categories, through: :categorizations
  
  attr_writer :category_names
  after_save  :assign_categories
  
  def category_names
    @category_names ||= categories.map(&:name).join(', ')
  end
  
  def to_param
    "#{id}-#{title.parameterize}"
  end
  
  private
  
  def assign_categories
    if @category_names
      self.categories = @category_names.split(', ').map do |name|
        Category.find_or_create_by_name(name)
      end
    end
  end
end

app/models/author.rb
class Author < ActiveRecord::Base
  validates :name,        presence: true
  validates :email,       presence: true
  validates :user_name,   presence: true,
                        uniqueness: true
  validates :password,    presence: true,
                            length: { minimum: 7 }

  attr_accessible :name, :user_name, :email, :password

  has_many :articles, dependent: :destroy

  attr_accessor :password
  before_save :encrypt_password
  
  def to_param
    "#{id}-#{name.parameterize}"
  end
  
  def self.authenticate(user_name, password)
    user = find_by_user_name(user_name)
    
    if user && user.hashed_password == BCrypt::Engine.hash_secret(password, user.salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.salt = BCrypt::Engine.generate_salt
      self.hashed_password = BCrypt::Engine.hash_secret(password, salt)
    end
  end
end

app/models/categories.rb
class Category < ActiveRecord::Base
  has_many :categorizations
  has_many :articles, through: :categorizations
end

app/models/categorization.rb
class Categorization < ActiveRecord::Base
  belongs_to :article
  belongs_to :category
end

app/models/categorizations.rb
class Categorization < ActiveRecord::Base
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name,   presence: true,
                   uniqueness: true
  
  has_many :categorizations, dependent: :destroy
  has_many :articles, through: :categorizations
  
  def to_param
    "#{id}-#{name.parameterize}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_author
  before_filter :current_author?, only: [:new, :create, :update, :destroy]

  def current_author?
    unless current_author
      redirect_to root_url, notice: "Please sign in"
    end
  end
  
  private
  
  def current_author
    @current_author ||= Author.find(session[:author_id]) if session[:author_id]
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  before_filter :get_article, only: [:show, :edit, :update, :destroy]
  
  def get_article
    @article = Article.find(params[:id])
  end
  
  # GET /articles
  def index
    @articles = Article.all
  end
  
  # GET /articles/1
  def show
  end
  
  # GET /articles/new
  def new
    @article = Article.new
  end
  
  # POST /articles
  def create
    @article = Article.new(params[:article])
    
    if @article.save
      # ArticleMailer.article_published(@article).deliver
      redirect_to @article, notice: "Article successfully created."
    else
      render action: "new"
    end
  end
  
  # PUT /articles/1
  def update
    @article.update_attributes(params[:article])
    
    redirect_to @article
  end
  
  # DELETE /articles/1
  def destroy
    @article.destroy
    
    respond_to do |format|
      format.html { 
        redirect_to articles_url
        flash[:notice] = "Article gone!"
      }
      format.js
    end
  end
  
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_filter :get_author, only: [:show, :edit, :update, :destroy]
  
  def get_author
    @author = Author.find(params[:id])
  end
  
  def index
    @authors = Author.includes(:articles).all
  end
  
  def new
    @author = Author.new
  end

  def create
    @author = Author.new(params[:author])

    if @author.save
      redirect_to @author, notice: "Author successfully created."
    else
      render action: "new"
    end
  end

  def update
    @author.update_attributes(params[:author])

    redirect_to @author
  end

  def destroy
    @author.destroy
    flash[:notice] = "Author gone!"
    redirect_to authors_url
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :get_category, only: [:show, :edit, :update, :destroy]
  
  def get_category
    @category = Category.find(params[:id])
  end
  
  def index
    @categories = Category.all
  end
  
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(params[:category])
    
    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category successfully created" }
      else
        format.html { render action: "new" }
      end
      format.js
    end
  end

  def update
    @category.update_attributes(params[:name])

    redirect_to @category
  end

  def destroy
    @category.destroy
    flash[:notice] = "Category gone!"
    redirect_to categories_url
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :current_author?
  
  def new
  end

  def create
    author = Author.authenticate(params[:user_name], params[:password])
    
    if author
      session[:author_id] = author.id
      redirect_to root_url, notice: "Signed in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end
  
  def destroy
    session[:author_id] = nil
    redirect_to root_url, notice: "Signed out!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |article_form| %>
	<% if @article.errors.any? %>
    <div class="error">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>
      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<ul>
		<li>
			<%= article_form.label :author_id %>
			<%= select('article', 'author_id', Author.all.collect {|a| [ a.name, a.id ] }, { include_blank: true }) %>
		</li>
		<li>
			<%= article_form.label :title %>
			<%= article_form.text_field :title %>
		</li>
		<li>
			<%= article_form.label :category_names, 'Categories' %>
			<%= article_form.text_field :category_names %>
		</li>
		<li>
			<%= article_form.label :body %>
			<%= article_form.text_area :body %>
		</li>
		<li class="button"><%= article_form.submit %></li>
	</ul>
<% end %>

app/views/articles/destroy.js.erb
$('#<%= dom_id(@article) %>').fadeOut();

app/views/articles/edit.html.erb
<% content_for :title, "Edit #{@article.title}" %>

<h1>Edit <%= @article.title %></h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<% content_for :title, "Articles archive" %>

<section class="hfeed">
	<h1>Articles archive</h1>

	<% @articles.reverse_each do |article| %>
		<article class="hentry">
			<h2 class="entry-title"><%= link_to article.title, article, rel: 'bookmark' %></h2>
			<div class="entry-summary">
				<%= raw truncate(article.body, length: 300) %>
				<p><%= link_to 'Read more', article, rel: 'nofollow' %></p>
			</div>
		</article>
	<% end %>
</section>

app/views/articles/new.html.erb
<% content_for :title, "Create a new article" %>

<h1>Create a new article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<% content_for :title, @article.title %>

<article class="hentry">
	<header>
		<h1 class="entry-title"><%= @article.title %></h1>
		
		<div class="article-meta">
			<p class="date"><time datetime="<%= @article.created_at.strftime("%Y-	%m-%d:%H:%M%z") %>" class="published updated" pubdate><%= @article.created_at.strftime("#{@article.created_at.day.ordinalize} %b %Y") %></time></p>
			<p class="vcard author">by <%= link_to @article.author.name, @article.author, class: 'fn n' %></p>

			<ul class="listless categories">
				<% @article.categories.each do |category| %>
					<li><%= link_to category.name, category, rel: 'tag' %></li>
				<% end %>
			</ul>
		</div>
		
		<% if current_author %>
			<ul class="inline article-actions">
				<li class="edit"><%= link_to 'Edit', edit_article_path(@article) %></li>
				<li class="delete"><%= link_to 'Delete', @article, confirm: "Are you sure you want to delete this article?", method: :delete %></li>
			</ul>
		<% end %>
	</header>

	<div class="entry-content">
		<%= raw @article.body %>
	</div>
</article>

app/views/authors/_form.html.erb
<%= form_for(@author) do |author_form| %>
	<% if @author.errors.any? %>
    <div class="error">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this article from being saved:</h2>
      <ul>
      <% @author.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<ul>
		<li>
			<%= author_form.label :name %>
			<%= author_form.text_field :name %>
		</li>
		<li>
			<%= author_form.label :user_name %>
			<%= author_form.text_field :user_name %>
		</li>
		<li>
			<%= author_form.label :email %>
			<%= author_form.email_field :email %>
		</li>
		<li>
			<%= author_form.label :password %>
			<%= author_form.password_field :password %>
		</li>
		<li class="button"><%= author_form.submit %></li>
	</ul>
<% end %>

app/views/authors/edit.html.erb
<% content_for :title, "Edit #{@author.name}" %>

<h1>Edit <%= @author.name %></h1>

<%= render 'form' %>

app/views/authors/index.html.erb
<% content_for :title, "Authors" %>

<h1>Authors</h1>

<ul>
	<% @authors.each do |author| %>
		<li><%= link_to author.name, author %> (<%= author.articles.length %>)</li>
	<% end %>
</ul>

app/views/authors/new.html.erb
<% content_for :title, "Create a new author" %>

<h1>Create a new author</h1>

<%= render 'form' %>

app/views/authors/show.html.erb
<% content_for :title, "#{@author.name}'s Articles" %>

<article class="hentry">
	<header>
		<h1><%= @author.name %>&rsquo;s Articles</h1>
		
		<% if current_author %>
			<ul class="inline article-actions">
				<li class="edit"><%= link_to 'Edit', edit_author_path(@author) %></li>
				<li class="delete"><%= link_to 'Delete', @author, confirm: "Are you sure you want to delete this author?", method: :delete %>
			</ul>
		<% end %>
	</header>
	
	<ul>
		<% @author.articles.reverse_each do |article| %>
			<%= content_tag_for(:li, article) do %>
				<%= link_to article.title, article, rel: 'bookmark' %>
				<% if current_author %>
					(<%= link_to 'Delete', article, method: :delete, remote: true, class: 'delete' %>)
				<% end %>
			<% end %>
		<% end %>
	</ul>
</article>

app/views/categories/_category.html.erb
<%= content_tag_for(:li, category) do %>
	<%= link_to category.name, category %> (<%= category.articles.length %>)</li>
<% end %>

app/views/categories/_form.html.erb
<%= form_for(@category) do |category_form| %>
	<% if @category.errors.any? %>
    <div class="error">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>
      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<ul>
		<li>
			<%= category_form.label :name %>
			<%= category_form.text_field :name %>
		</li>
		<li class="button"><%= category_form.submit %></li>
	</ul>
<% end %>

app/views/categories/create.js.erb
<% if @category.new_record? %>
	$('input#category_name').effect('highlight', {color: 'red});
<% else %>
	$('ul#categories').append("<%= escape_javascript(render @category) %>");
	$('li#<%= dom_id(@category) %>').effect('highlight');
<% end %>

app/views/categories/edit.html.erb
<% content_for :title, "Edit the #{@category.name} category" %>

<h1>Edit the <%= @category.name %> category</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<% content_for :title, "Categories" %>

<h1>Categories</h1>

<ul id="categories">
	<%= render @categories %>
</ul>

<%= form_for(Category.new, remote: true) do |category_form| %>
	<ul>
		<li>
			<%= category_form.label :name %>
			<%= category_form.text_field :name %>
		</li>
		<li class="button"><%= category_form.submit %></li>
	</ul>
<% end %>

app/views/categories/new.html.erb
<% content_for :title, "Add a new category to the list" %>

<h1>Add a new category to the list</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<% content_for :title, "List of articles categorized with: #{@category.name}" %>

<article class="hentry">
	<header>
		<h1>List of articles categorized with: <%= @category.name %></h1>
		
		<% if current_author %>
			<ul class="inline article-actions">
				<li class="edit"><%= link_to 'Edit', edit_category_path(@category) %></li>
				<li class="delete"><%= link_to 'Delete', @category, confirm: "Are you sure you want to delete this category?", method: :delete %>
			</ul>
		<% end %>
	</header>
	
	<div class="entry-content hfeed">
		<% @category.articles.reverse_each do |article| %>
			<article class="hentry">
				<h2 class="entry-title"><%= link_to article.title, article, rel: 'bookmark' %></h2>
				<div class="entry-summary">
					<%= raw truncate(article.body, length: 300) %>
					<p><%= link_to 'Read more', article, rel: 'nofollow' %></p>
				</div>
			</article>
		<% end %>
	</div>
</article>

app/views/layouts/application.html.erb
<!doctype html>
<!--[if IE 7]><html id="brads-ruby-blog-com" class="no-js ie7" lang="en-US"><![endif]-->
<!--[if IE 8]><html id="brads-ruby-blog-com" class="no-js ie8" lang="en-US"><![endif]-->
<!--[if gt IE 8]><!--><html id="brads-ruby-blog-com" class="no-js" lang="en-US"><!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	
  <title><%= yield :title %> | Brad&rsquo;s Ruby Blog</title>

  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= stylesheet_link_tag 'application' %>
  <%= csrf_meta_tags %>

  <link rel="home" href="http://brads-ruby-blog.heroku.com" title="Home page" />
  <link rel="author" href="http://brads-ruby-blog.heroku.com/humans.txt" />
  <script>(function(H){H.className=H.className.replace(/\bno-js\b/,'js')})(document.documentElement)</script>
</head>
<body>

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, id: "flash-#{name}", class: "flash" %>
<% end %>

<nav>
	<ul class="inline">
		<li><%= link_to 'Archive', articles_path %></li>
		<li><%= link_to 'Authors', authors_path %></li>
		<li><%= link_to 'Categories', categories_path %></li>
	</ul>
</nav>

<%= yield %>

<div id="menu">
	<% if current_author %>
		<ul class="inline">
			<li><%= link_to 'Create an article', new_article_path %></li>
			<li><%= link_to 'Add an author', new_author_path %></li>
			<li><%= link_to 'Create a category', new_category_path %></li>
		</ul>
		<p>Signed in as <%= link_to current_author.name, current_author %>, <%= link_to 'Sign out', sign_out_path %></p>
	<% else %>
		<p><%= link_to 'Sign in', sign_in_path %></p>
	<% end %>
</div><!-- /#menu -->

<%= javascript_include_tag 'application' %>

<!-- asynchronous google analytics change the UA-XXXXX-X to be your site's ID -->
<script>
  var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview'],['_trackPageLoadTime']];
  (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
  g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
  s.parentNode.insertBefore(g,s)}(document,'script'));
</script>

<!--[if lt IE 7 ]>
<script defer src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.3/CFInstall.min.js"></script>
<script defer>window.attachEvent('onload',function(){CFInstall.check({mode:'overlay'})})</script>
<![endif]-->
</body>
</html>